name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install cmake, lcov
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake lcov
        pip install --user cpp-coveralls

    - name: Build code
      run: bash ./build.sh default && bash ./build.sh unit_tests

    - name: run unit tests
      working-directory: src/unit-tests/build
      run: ./runTests

    - name: Gather tests coverage data
      working-directory: src/unit-tests/build
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '*/test/*' '*/third_party/*' --output-file coverage.info
        lcov --list coverage.info
        coveralls
