name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install cmake, lcov
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake lcov
        pip install --user cpp-coveralls

    - name: Install Coveralls uploader
      run: |
        gem install coveralls-lcov

    - name: Build code and unit tests
      run: bash ./build.sh all

    - name: Run unit tests / Gather coverage data
      working-directory: src/unit-tests/build
      run: |
        ./runTests
        lcov --capture --directory . --output-file coverage.info --no-external

    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        coveralls-lcov src/unit-tests/build/coverage.info

