name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Clang
      run: sudo apt-get install -y clang

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        
    - name: Build code
      run: bash ./build.sh default && bash ./build.sh unit_tests

    - name: run unit tests
      working-directory: src/unit-tests/build
      run: ./runTests